export const SET_LISTING_DATA = "SET_LISTING_DATA";
export const RESET_LISTING_DATA = "RESET_LISTING_DATA";

export const LESS_AJAX_CALL_COUNT = 'LESS_AJAX_CALL_COUNT';
export const ADD_AJAX_CALL_COUNT = 'ADD_AJAX_CALL_COUNT';

export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";